version: '3.8'

services:
  face-recognition:
    build: .
    container_name: face-recognition
    ports:
      - "8000:8000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - insightface_models:/root/.insightface/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  insightface_models: