name: cuda118
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - cudnn=8.9.2
  - numpy=1.23.5
  - scipy=1.10.1
  - pip=23.3.1
  - pip:
    - onnxruntime-gpu==1.16.3
    - insightface==0.7.3
    - opencv-python-headless==4.10.0.84
    - fastapi==0.115.6
    - uvicorn==0.34.0
    - albumentations==1.3.1
    - boto3==1.35.91
    - coloredlogs==15.0.1
    - easydict==1.10
    - python-dotenv==1.0.1
    - scikit-image==0.19.3
    - scikit-learn==1.2.2
    - watchtower==3.3.1
    - matplotlib==3.7.1
    - pydantic==2.10.4
    - pymongo==4.10.1
    - Pillow==9.5.0